use anyhow::{bail, Context, Result};
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::plan::{self, Plan, AGENTS};

pub const BRANCH: &str = "chore/consolidate-agent-instructions";
pub const COMMIT_MSG: &str = "chore: consolidate agent instruction files into AGENTS.md";

#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Strategy {
    /// Migrate inside a temporary `git worktree` — the checkout is never touched.
    Worktree,
    /// Create the branch in the repo itself (requires clean tree), restore after.
    InPlace,
}

#[derive(Debug, Default, Serialize)]
pub struct PrOutcome {
    pub strategy: Option<Strategy>,
    pub branch: Option<String>,
    pub committed: bool,
    pub pushed: bool,
    pub pr_url: Option<String>,
    pub skipped: Option<String>,
    pub warnings: Vec<String>,
}

/// Env that makes git/gh fail fast instead of hanging on prompts
/// (credentials, ssh passphrases, pinentry) in headless runs.
fn no_prompt_env(cmd: &mut Command) -> &mut Command {
    cmd.env("GIT_TERMINAL_PROMPT", "0")
        .env("GIT_SSH_COMMAND", "ssh -oBatchMode=yes")
        .env("GCM_INTERACTIVE", "Never")
}

fn git(repo: &Path, args: &[&str]) -> Result<String> {
    let out = no_prompt_env(Command::new("git").arg("-C").arg(repo).args(args))
        .output()
        .context("failed to spawn git")?;
    if !out.status.success() {
        bail!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn git_ok(repo: &Path, args: &[&str]) -> bool {
    no_prompt_env(Command::new("git").arg("-C").arg(repo).args(args))
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// True when `git status --porcelain` is empty (no modified or untracked files).
pub fn is_clean(repo: &Path) -> bool {
    git(repo, &["status", "--porcelain"])
        .map(|s| s.is_empty())
        .unwrap_or(false)
}

/// Base ref to branch from: `origin/HEAD` after a best-effort fetch, else `HEAD`.
fn base_ref(repo: &Path) -> String {
    let _ = git(repo, &["fetch", "origin", "--quiet"]);
    if git_ok(repo, &["rev-parse", "--verify", "origin/HEAD"]) {
        "origin/HEAD".into()
    } else {
        "HEAD".into()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RemoteKind {
    Github,
    Gitlab,
    Other,
}

pub fn remote_kind(repo: &Path) -> RemoteKind {
    let Ok(url) = git(repo, &["remote", "get-url", "origin"]) else {
        return RemoteKind::Other;
    };
    if url.contains("github.") {
        RemoteKind::Github
    } else if url.contains("gitlab.") {
        RemoteKind::Gitlab
    } else {
        RemoteKind::Other
    }
}

fn cli_available(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

const PR_BODY: &str = "Consolidates agent instruction files (`CLAUDE.md` and friends) into `AGENTS.md`.\n\
\n\
Claude Code ≥2.1.277 falls back to `AGENTS.md` when no `CLAUDE.md` exists,\n\
and Codex, Cursor, Copilot, Zed and friends read it natively —\n\
so a single file now serves every agent.\n\
\n\
Generated by [dump-shitty-claude-md](https://github.com/LivioGama/dump-shitty-claude-md).";

/// `gh pr create`, falling back to the URL of an existing PR for the branch.
fn create_github_pr(dir: &Path, outcome: &mut PrOutcome) -> Result<()> {
    if !cli_available("gh") {
        outcome.warnings.push("gh CLI not found — PR not created".into());
        return Ok(());
    }
    let out = no_prompt_env(
        Command::new("gh")
            .arg("pr")
            .arg("create")
            .args(["--title", COMMIT_MSG, "--body", PR_BODY, "--head", BRANCH])
            .current_dir(dir),
    )
    .output()
    .context("failed to spawn gh")?;
    if out.status.success() {
        outcome.pr_url = Some(String::from_utf8_lossy(&out.stdout).trim().to_string());
        return Ok(());
    }
    // Create failed — maybe a PR for this branch already exists.
    let existing = no_prompt_env(
        Command::new("gh")
            .args(["pr", "list", "--head", BRANCH, "--json", "url", "--jq"])
            .arg(".[0].url")
            .current_dir(dir),
    )
    .output()
    .ok()
    .filter(|o| o.status.success())
    .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
    .filter(|u| !u.is_empty());
    if let Some(url) = existing {
        outcome.pr_url = Some(url);
        outcome.warnings.push("PR already existed for branch".into());
    } else {
        outcome.warnings.push(format!(
            "gh pr create failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

/// `glab mr create`; the MR URL is scraped from the last http line of output.
fn create_gitlab_pr(dir: &Path, outcome: &mut PrOutcome) -> Result<()> {
    if !cli_available("glab") {
        outcome.warnings.push("glab CLI not found — MR not created".into());
        return Ok(());
    }
    let out = no_prompt_env(
        Command::new("glab")
            .args(["mr", "create", "--title", COMMIT_MSG, "--description"])
            .arg(PR_BODY)
            .args(["--source-branch", BRANCH, "--yes"])
            .current_dir(dir),
    )
    .output()
    .context("failed to spawn glab")?;
    if out.status.success() {
        let text = String::from_utf8_lossy(&out.stdout);
        outcome.pr_url = text
            .lines()
            .rfind(|l| l.contains("http"))
            .map(str::trim)
            .map(str::to_owned);
    } else {
        outcome.warnings.push(format!(
            "glab mr create failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

fn commit_push_pr(dir: &Path, repo_for_push: &Path, rels: &[PathBuf], outcome: &mut PrOutcome) -> Result<()> {
    // Per-path best-effort adds: a pathspec that matches neither worktree nor
    // index (e.g. a source file never tracked at the worktree base) is a hard
    // error, but there may simply be nothing to stage for that path.
    let mut paths: Vec<String> = rels
        .iter()
        .map(|r| r.to_string_lossy().to_string())
        .collect();
    paths.push(AGENTS.into());
    for p in &paths {
        let _ = git_ok(dir, &["add", "-A", "--", p]);
    }

    // Nothing staged → nothing to commit (can happen if files were untracked+ignored).
    let pathspecs: Vec<&str> = paths.iter().map(String::as_str).collect();
    let mut args = vec!["status", "--porcelain", "--"];
    args.extend(pathspecs.iter());
    if git(dir, &args)?.is_empty() {
        outcome.warnings.push("nothing staged — files may be gitignored".into());
        return Ok(());
    }

    // Index already contains exactly our staged paths — commit it wholesale
    // (a pathspec here could itself fail to match).
    git(dir, &["commit", "-m", COMMIT_MSG])?;
    outcome.committed = true;

    match git(dir, &["push", "-u", "origin", BRANCH]) {
        Ok(_) => outcome.pushed = true,
        Err(e) => {
            outcome.warnings.push(format!("push failed: {e:#}"));
            return Ok(());
        }
    }

    match remote_kind(repo_for_push) {
        RemoteKind::Github => create_github_pr(dir, outcome),
        RemoteKind::Gitlab => create_gitlab_pr(dir, outcome),
        RemoteKind::Other => {
            outcome
                .warnings
                .push("origin is not github/gitlab — PR not created".into());
            Ok(())
        }
    }
}

/// Source paths of the migrating plans, relative to the repo root.
fn rel_paths(plans: &[&Plan]) -> Vec<PathBuf> {
    plans.iter().map(|p| p.file.clone()).collect()
}

/// Worktree strategy: branch off `origin/HEAD` in a temp worktree, mirror the
/// working-tree state of all affected files, migrate, commit, push, PR, clean up.
fn run_worktree(repo: &Path, plans: &[&Plan], outcome: &mut PrOutcome) -> Result<()> {
    let base = base_ref(repo);
    let tmp = std::env::temp_dir().join(format!(
        "dscm-wt-{}-{}",
        std::process::id(),
        repo.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("repo")
    ));
    let tmp_str = tmp.to_string_lossy().to_string();

    // Branch may already exist from a previous run → retry without -b.
    if git(repo, &["worktree", "add", "-b", BRANCH, &tmp_str, &base]).is_err() {
        git(repo, &["worktree", "add", &tmp_str, BRANCH])
            .context("git worktree add failed")?;
    }
    outcome.branch = Some(BRANCH.into());

    let rels = rel_paths(plans);
    let result = (|| -> Result<()> {
        // Mirror working-tree state of every affected file into the worktree so
        // uncommitted edits/untracked files are preserved in the PR.
        for rel in rels.iter().chain(std::iter::once(&PathBuf::from(AGENTS))) {
            let src = repo.join(rel);
            let dst = tmp.join(rel);
            if src.symlink_metadata().is_ok() {
                if let Some(parent) = dst.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::copy(&src, &dst)
                    .with_context(|| format!("copy {}", src.display()))?;
            } else if dst.exists() {
                std::fs::remove_file(&dst)?;
            }
        }
        for p in plans {
            plan::apply(&tmp, &p.file, p.action)?;
        }
        commit_push_pr(&tmp, repo, &rels, outcome)
    })();

    let _ = git(repo, &["worktree", "remove", "--force", &tmp_str]);
    result
}

/// In-place strategy: branch in the user's checkout (requires clean tree),
/// migrate, commit, push, PR, then restore the previous branch.
fn run_in_place(repo: &Path, plans: &[&Plan], outcome: &mut PrOutcome) -> Result<()> {
    if !is_clean(repo) {
        bail!("working tree is dirty — use the worktree strategy instead");
    }
    let prev = git(repo, &["branch", "--show-current"])?;

    let base = base_ref(repo);
    if base == "origin/HEAD" {
        let ahead = git(repo, &["rev-list", "--count", "origin/HEAD..HEAD"])
            .unwrap_or_else(|_| "0".into());
        if ahead != "0" {
            outcome.warnings.push(format!(
                "HEAD is {ahead} commit(s) ahead of origin/HEAD — PR will include them"
            ));
        }
    }

    if git(repo, &["checkout", "-b", BRANCH]).is_err() {
        git(repo, &["checkout", BRANCH])?;
    }
    outcome.branch = Some(BRANCH.into());

    let result = (|| -> Result<()> {
        for p in plans {
            plan::apply(repo, &p.file, p.action)?;
        }
        commit_push_pr(repo, repo, &rel_paths(plans), outcome)
    })();

    if !prev.is_empty() {
        let _ = git(repo, &["checkout", &prev]);
    }
    result
}

pub fn run(repo: &Path, plans: &[&Plan], strategy: Strategy) -> PrOutcome {
    let mut outcome = PrOutcome {
        strategy: Some(strategy),
        ..Default::default()
    };
    let res = match strategy {
        Strategy::Worktree => run_worktree(repo, plans, &mut outcome),
        Strategy::InPlace => run_in_place(repo, plans, &mut outcome),
    };
    if let Err(e) = res {
        outcome.warnings.push(format!("{e:#}"));
    }
    outcome
}
